"""CA operations: clients, compliance cases, requirements, and the agent.

Adds the twelve tables the client-operations product needs, and three
nullable columns on ``documents`` so a document can belong to a client and
a case. Nullable on purpose: the existing extraction API uploads documents
with neither, and every current caller keeps working untouched.

Revision ID: 0006_ca_operations
Revises: 0005_tally
Create Date: 2026-09-19
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Declared here rather than imported from app.db.base: a migration that
# imports application code stops being a record of what the schema was.
ID = sa.String(40)
TS = sa.DateTime(timezone=True)
JSON_TYPE = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")
revision: str = "0006_ca_operations"
down_revision: str | None = "0005_tally"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_policies",
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("allow_whatsapp", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("allow_voice_calls", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            "allow_document_processing", sa.Boolean(), server_default=sa.true(), nullable=False
        ),
        sa.Column("allow_auto_followup", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column(
            "allow_auto_escalation", sa.Boolean(), server_default=sa.true(), nullable=False
        ),
        sa.Column(
            "max_messages_per_day", sa.Integer(), server_default=sa.text("(200)"), nullable=False
        ),
        sa.Column(
            "max_calls_per_day", sa.Integer(), server_default=sa.text("(20)"), nullable=False
        ),
        sa.Column(
            "max_followups_per_case", sa.Integer(), server_default=sa.text("3"), nullable=False
        ),
        sa.Column(
            "first_reminder_hours", sa.Integer(), server_default=sa.text("(24)"), nullable=False
        ),
        sa.Column(
            "second_reminder_hours", sa.Integer(), server_default=sa.text("(48)"), nullable=False
        ),
        sa.Column(
            "voice_call_after_hours", sa.Integer(), server_default=sa.text("(72)"), nullable=False
        ),
        sa.Column(
            "classification_threshold",
            sa.String(length=10),
            server_default=sa.text("'0.80'"),
            nullable=False,
        ),
        sa.Column("local_ai_only", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            "quiet_hours_start", sa.Integer(), server_default=sa.text("(21)"), nullable=False
        ),
        sa.Column("quiet_hours_end", sa.Integer(), server_default=sa.text("9"), nullable=False),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_policies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("pk_agent_policies")),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=True),
        sa.Column("client_code", sa.String(length=60), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("whatsapp_phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("pan", sa.String(length=10), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "preferred_channel",
            sa.String(length=20),
            server_default=sa.text("'whatsapp'"),
            nullable=False,
        ),
        sa.Column(
            "preferred_language",
            sa.String(length=20),
            server_default=sa.text("'en'"),
            nullable=False,
        ),
        sa.Column(
            "allow_automated_contact", sa.Boolean(), server_default=sa.true(), nullable=False
        ),
        sa.Column("automation_paused_reason", sa.Text(), nullable=True),
        sa.Column(
            "contact_state",
            sa.String(length=30),
            server_default=sa.text("'not_contacted'"),
            nullable=False,
        ),
        sa.Column("last_contacted_at", TS, nullable=True),
        sa.Column("last_response_at", TS, nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_clients_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint(
            "organization_id", "client_code", name="uq_clients_organization_id_client_code"
        ),
    )
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.create_index("ix_clients_org_gstin", ["organization_id", "gstin"], unique=False)
        batch_op.create_index("ix_clients_org_status", ["organization_id", "status"], unique=False)
        batch_op.create_index(
            "ix_clients_org_whatsapp", ["organization_id", "whatsapp_phone"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_clients_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "client_facts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", JSON_TYPE, nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=True),
        sa.Column("expires_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_facts_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_client_facts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_facts")),
        sa.UniqueConstraint("client_id", "key", name="uq_client_facts_client_id_key"),
    )
    with op.batch_alter_table("client_facts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_client_facts_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_client_facts_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "compliance_cases",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("period", sa.String(length=40), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'not_started'"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_compliance_cases_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_compliance_cases_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compliance_cases")),
        sa.UniqueConstraint(
            "client_id", "type", "period", name="uq_compliance_cases_client_id_type"
        ),
    )
    with op.batch_alter_table("compliance_cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_compliance_cases_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            "ix_compliance_cases_org_deadline", ["organization_id", "deadline"], unique=False
        )
        batch_op.create_index(
            "ix_compliance_cases_org_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_compliance_cases_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=30), server_default=sa.text("'open'"), nullable=False),
        sa.Column("last_message_at", TS, nullable=True),
        sa.Column("last_inbound_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_conversations_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_conversations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "organization_id", "client_id", "channel", name="uq_conversations_client_channel"
        ),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            "ix_conversations_org_last_message",
            ["organization_id", "last_message_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_conversations_org_phone", ["organization_id", "phone"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "agent_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=True),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.String(length=40), nullable=True),
        sa.Column("details", JSON_TYPE, nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["compliance_cases.id"],
            name=op.f("fk_agent_events_case_id_compliance_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_agent_events_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_events")),
    )
    with op.batch_alter_table("agent_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_events_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            "ix_agent_events_client_created", ["client_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_events_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            "ix_agent_events_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_events_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_events_run_id"), ["run_id"], unique=False)

    op.create_table(
        "agent_jobs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=True),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("payload", JSON_TYPE, nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'queued'"), nullable=False
        ),
        sa.Column("available_at", TS, nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("attempt_number", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("claimed_at", TS, nullable=True),
        sa.Column("completed_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["compliance_cases.id"],
            name=op.f("fk_agent_jobs_case_id_compliance_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_agent_jobs_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_jobs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_jobs")),
        sa.UniqueConstraint("dedupe_key", name="uq_agent_jobs_dedupe_key"),
    )
    with op.batch_alter_table("agent_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_jobs_available_at"), ["available_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_jobs_case_id"), ["case_id"], unique=False)
        batch_op.create_index("ix_agent_jobs_claim", ["status", "available_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_jobs_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            "ix_agent_jobs_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_jobs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "calls",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'scheduled'"), nullable=False
        ),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("provider_call_id", sa.String(length=200), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("detected_intent", sa.String(length=40), nullable=True),
        sa.Column("intent_details", JSON_TYPE, nullable=False),
        sa.Column("started_at", TS, nullable=True),
        sa.Column("ended_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["compliance_cases.id"],
            name=op.f("fk_calls_case_id_compliance_cases"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_calls_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_calls_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        sa.UniqueConstraint(
            "organization_id", "provider_call_id", name="uq_calls_provider_call_id"
        ),
    )
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calls_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            "ix_calls_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_calls_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "document_requirements",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=False),
        sa.Column("document_type", sa.String(length=40), nullable=False),
        sa.Column("required", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'missing'"), nullable=False
        ),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("received_document_id", sa.String(length=40), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("requested_at", TS, nullable=True),
        sa.Column("received_at", TS, nullable=True),
        sa.Column("settled_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["compliance_cases.id"],
            name=op.f("fk_document_requirements_case_id_compliance_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_document_requirements_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["received_document_id"],
            ["documents.id"],
            name=op.f("fk_document_requirements_received_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_requirements")),
        sa.UniqueConstraint(
            "case_id", "document_type", name="uq_document_requirements_case_id_document_type"
        ),
    )
    with op.batch_alter_table("document_requirements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_requirements_case_id"), ["case_id"], unique=False
        )
        batch_op.create_index(
            "ix_document_requirements_org_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_requirements_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=False),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("document_id", sa.String(length=40), nullable=True),
        sa.Column("media_reference", sa.String(length=500), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("provider_message_id", sa.String(length=200), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'queued'"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("detected_intent", sa.String(length=40), nullable=True),
        sa.Column("intent_details", JSON_TYPE, nullable=False),
        sa.Column("sent_by_agent", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["compliance_cases.id"],
            name=op.f("fk_messages_case_id_compliance_cases"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_messages_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_messages_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_messages_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "organization_id", "provider_message_id", name="uq_messages_provider_message_id"
        ),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            "ix_messages_conversation_created", ["conversation_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "exceptions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=True),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("document_id", sa.String(length=40), nullable=True),
        sa.Column("requirement_id", sa.String(length=40), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column(
            "severity", sa.String(length=20), server_default=sa.text("'warning'"), nullable=False
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", JSON_TYPE, nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
        sa.Column("assigned_to_user_id", sa.String(length=40), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_by_user_id", sa.String(length=40), nullable=True),
        sa.Column("resolved_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_exceptions_assigned_to_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["compliance_cases.id"],
            name=op.f("fk_exceptions_case_id_compliance_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_exceptions_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_exceptions_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_exceptions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["document_requirements.id"],
            name=op.f("fk_exceptions_requirement_id_document_requirements"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_exceptions_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exceptions")),
        sa.UniqueConstraint("organization_id", "dedupe_key", name="uq_exceptions_dedupe_key"),
    )
    with op.batch_alter_table("exceptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exceptions_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_exceptions_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            "ix_exceptions_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_exceptions_org_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exceptions_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=40), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=True),
        sa.Column("case_id", sa.String(length=40), nullable=True),
        sa.Column("exception_id", sa.String(length=40), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "priority", sa.String(length=20), server_default=sa.text("'normal'"), nullable=False
        ),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
        sa.Column("assigned_to_user_id", sa.String(length=40), nullable=True),
        sa.Column(
            "created_by", sa.String(length=20), server_default=sa.text("'agent'"), nullable=False
        ),
        sa.Column("due_at", TS, nullable=True),
        sa.Column("completed_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("updated_at", TS, nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_tasks_assigned_to_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["compliance_cases.id"],
            name=op.f("fk_tasks_case_id_compliance_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_tasks_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exceptions.id"],
            name=op.f("fk_tasks_exception_id_exceptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tasks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_client_id"), ["client_id"], unique=False)
        batch_op.create_index("ix_tasks_org_due", ["organization_id", "due_at"], unique=False)
        batch_op.create_index("ix_tasks_org_status", ["organization_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tasks_organization_id"), ["organization_id"], unique=False
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_id", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("case_id", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("classified_type", sa.String(length=40), nullable=True))
        batch_op.add_column(
            sa.Column("classification_confidence", sa.String(length=10), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "source", sa.String(length=20), server_default=sa.text("'api'"), nullable=False
            )
        )
        batch_op.create_index(batch_op.f("ix_documents_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_client_id"), ["client_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_documents_client_id_clients"),
            "clients",
            ["client_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_documents_case_id_compliance_cases"),
            "compliance_cases",
            ["case_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_documents_case_id_compliance_cases"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("fk_documents_client_id_clients"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_documents_client_id"))
        batch_op.drop_index(batch_op.f("ix_documents_case_id"))
        batch_op.drop_column("source")
        batch_op.drop_column("classification_confidence")
        batch_op.drop_column("classified_type")
        batch_op.drop_column("case_id")
        batch_op.drop_column("client_id")

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_organization_id"))
        batch_op.drop_index("ix_tasks_org_status")
        batch_op.drop_index("ix_tasks_org_due")
        batch_op.drop_index(batch_op.f("ix_tasks_client_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("exceptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exceptions_organization_id"))
        batch_op.drop_index("ix_exceptions_org_status")
        batch_op.drop_index("ix_exceptions_org_created")
        batch_op.drop_index(batch_op.f("ix_exceptions_client_id"))
        batch_op.drop_index(batch_op.f("ix_exceptions_case_id"))

    op.drop_table("exceptions")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_organization_id"))
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))
        batch_op.drop_index("ix_messages_conversation_created")
        batch_op.drop_index(batch_op.f("ix_messages_client_id"))

    op.drop_table("messages")
    with op.batch_alter_table("document_requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_requirements_organization_id"))
        batch_op.drop_index("ix_document_requirements_org_status")
        batch_op.drop_index(batch_op.f("ix_document_requirements_case_id"))

    op.drop_table("document_requirements")
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calls_organization_id"))
        batch_op.drop_index("ix_calls_org_created")
        batch_op.drop_index(batch_op.f("ix_calls_client_id"))

    op.drop_table("calls")
    with op.batch_alter_table("agent_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_jobs_organization_id"))
        batch_op.drop_index("ix_agent_jobs_org_created")
        batch_op.drop_index(batch_op.f("ix_agent_jobs_client_id"))
        batch_op.drop_index("ix_agent_jobs_claim")
        batch_op.drop_index(batch_op.f("ix_agent_jobs_case_id"))
        batch_op.drop_index(batch_op.f("ix_agent_jobs_available_at"))

    op.drop_table("agent_jobs")
    with op.batch_alter_table("agent_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_events_run_id"))
        batch_op.drop_index(batch_op.f("ix_agent_events_organization_id"))
        batch_op.drop_index("ix_agent_events_org_created")
        batch_op.drop_index(batch_op.f("ix_agent_events_client_id"))
        batch_op.drop_index("ix_agent_events_client_created")
        batch_op.drop_index(batch_op.f("ix_agent_events_case_id"))
        batch_op.drop_index(batch_op.f("ix_agent_events_action"))

    op.drop_table("agent_events")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_organization_id"))
        batch_op.drop_index("ix_conversations_org_phone")
        batch_op.drop_index("ix_conversations_org_last_message")
        batch_op.drop_index(batch_op.f("ix_conversations_client_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("compliance_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_compliance_cases_organization_id"))
        batch_op.drop_index("ix_compliance_cases_org_status")
        batch_op.drop_index("ix_compliance_cases_org_deadline")
        batch_op.drop_index(batch_op.f("ix_compliance_cases_client_id"))

    op.drop_table("compliance_cases")
    with op.batch_alter_table("client_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_facts_organization_id"))
        batch_op.drop_index(batch_op.f("ix_client_facts_client_id"))

    op.drop_table("client_facts")
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clients_organization_id"))
        batch_op.drop_index("ix_clients_org_whatsapp")
        batch_op.drop_index("ix_clients_org_status")
        batch_op.drop_index("ix_clients_org_gstin")

    op.drop_table("clients")
    op.drop_table("agent_policies")
    # ### end Alembic commands ###
